base_url = "https://fantasy.motogp.com/json/"
riders_url = base_url+"riders.json"
squads_url = base_url+"squads.json"
events_url = base_url+"events.json"
constructors_url = base_url+"constructors.json"